# Generated by Django 4.1 on 2022-08-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspermit',
            name='bgry_permit_renew',
            field=models.DateField(auto_now=True, verbose_name='Brgy Permit Renew'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='bir_0605_end',
            field=models.DateField(auto_now=True, verbose_name='BIR 605 End'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='bir_0605_start',
            field=models.DateField(auto_now=True, verbose_name='BIR 605 Start'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='brgy_permit_end',
            field=models.DateField(auto_now=True, verbose_name='Brgy Permit End'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='brgy_permit_start',
            field=models.DateField(auto_now=True, verbose_name='Brgy Permit Start'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='business_permit_end',
            field=models.DateField(auto_now=True, verbose_name='Business Permit End'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='business_permit_renew',
            field=models.DateField(auto_now=True, verbose_name='Business Permit Renew'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='business_permit_start',
            field=models.DateField(auto_now=True, verbose_name='Business Permit Start'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='cedula_end',
            field=models.DateField(auto_now=True, verbose_name='Cedula End'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='cedula_start',
            field=models.DateField(auto_now=True, verbose_name='Cedula Start'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='cert_of_final_electrical_inspection_end',
            field=models.DateField(auto_now=True, verbose_name='Certification of Final Electrical Inspection End'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='cert_of_final_electrical_inspection_start',
            field=models.DateField(auto_now=True, verbose_name='Certification of Final Electrical Inspection Start'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='company',
            field=models.CharField(default='APTGSI', max_length=245, verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='enviromental_clearance_end',
            field=models.DateField(auto_now=True, verbose_name='Enviromental Clearance End'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='enviromental_clearance_start',
            field=models.DateField(auto_now=True, verbose_name='Enviromental Clearance Start'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='fsic_end',
            field=models.DateField(auto_now=True, verbose_name='FSIC End'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='fsic_start',
            field=models.DateField(auto_now=True, verbose_name='FSIC Start'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='insurance_end',
            field=models.DateField(auto_now=True, verbose_name='Insurance End'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='insurance_start',
            field=models.DateField(auto_now=True, verbose_name='Insurance Start'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='location',
            field=models.CharField(default='Muntinlupa City', max_length=245, verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='sanitary_end',
            field=models.DateField(auto_now=True, verbose_name='Sanitary Permit End'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='sanitary_start',
            field=models.DateField(auto_now=True, verbose_name='Sanitary Permit Start'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='signage_permit_end',
            field=models.DateField(auto_now=True, verbose_name='Signage Permit End'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='signage_permit_start',
            field=models.DateField(auto_now=True, verbose_name='Signage Permit Start'),
        ),
        migrations.AddField(
            model_name='businesspermit',
            name='zoning',
            field=models.CharField(default='N/A', max_length=245, verbose_name='Zoning'),
        ),
        migrations.AlterField(
            model_name='businesspermit',
            name='personel_assignment',
            field=models.CharField(default='Melvin Daza', max_length=245, verbose_name='Personel Assignment'),
        ),
        migrations.AlterField(
            model_name='businesspermit',
            name='stores',
            field=models.CharField(default='ATC 1', max_length=245, verbose_name='Stores'),
        ),
    ]
